### ISSUE TITLE
Nuget Package restore not working

### ISSUE THREAD

**Issue by valadas** [DNNCommunity/DNN.Announcements#11]
As reported by @EPTamminga the build fails due to failed nuget package restore. Here is his error message:

Error NuGet Package restore failed for project DotNetNuke.Announcements: Unable to find version '9.1.1.105' of package 'DotNetNuke.Instrumentation'. C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\: Package 'DotNetNuke.Instrumentation.9.1.1.105' is not found on source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\'. https://api.nuget.org/v3/index.json: Package 'DotNetNuke.Instrumentation.9.1.1.105' is not found on source 'https://api.nuget.org/v3/index.json'. https://www.nuget.org/api/v2/curated-feeds/microsoftdotnet/: Package 'DotNetNuke.Instrumentation.9.1.1.105' is not found on source 'https://www.nuget.org/api/v2/curated-feeds/microsoftdotnet/'. . 0

I am investigating that shortly on a clean windows/Visual Studio install to make sure building the module is as easy as possible.

**Comment by jgathairu** [comment]
Same issue. Has someone figured out how to do a proper restore

**Comment by valadas** [comment]
@EPTamminga , this pull request should solve this issue, when you can, please try a build and merge if it works, please merge, I don't think a new release is needed since people who download the release should not need to build from sources...

@jgathairu in the meantime if you need to build before this is merged, you can take a loot at the changes in this pull request, just a couple version numbers to replace here and there.
