### ISSUE TITLE
Edit URL Uses Old DNN NavigateURL Format

### ISSUE THREAD

**Issue by ej401** [DNNCommunity/DNN.Announcements#18]
## Describe the bug
Something I just noticed when trying to edit an existing announcement is that the format of the edit URL is now different. Here are some samples from our test site:

Old Format (throws 404): [Root Site URL]/Home/tabid/73/ctl/Edit/itemid/325/mid=2044?popUp=true

New Format (works): [Root Site URL]/Home/tabid/73/ctl/Edit/mid/2044/itemid/325/Default.aspx?popUp=true

## Software Versions
- DNN: 09.02.00
- Module: 07.02.00

## To Reproduce
Create an announcement and then try to edit it.

## Expected behavior
The edit form should load.

Thanks,
Eric

**Comment by valadas** [comment]
Can only reproduce with humanfriendly url mode
