### ISSUE TITLE
Separator Template field is not saving

### ISSUE THREAD

**Issue by dnndiva** [DNNCommunity/DNN.Announcements#27]
## Describe the bug
Updating Separator Template field is not working. It just goes back to blank.

## Software Versions
- DNN: 9.2.0
- Module: 7.2.0

## To Reproduce
1. Go to Template Configuration
2. Add any HTML on the Separator Template field
3. Click on Update
4. Added HTML is not displayed nor is present on rendered markup.
5. Go to Template Configuration again
6. Find Separator Template field blank

## Expected behavior
Added HTML to be saved so the HTML can be displayed and not erased when updating Template Configuration.

## Screenshots
N/A

## Error log
08/28/2018 18:55:50
Module Updated
Module logs as updated, but it is not updated.

## Additional context
Just tested the other template fields. The same behavior happens when editing Alternate Item Template field. All other fields (Header, Item and Footer) work as expected.

**Comment by krlaframboise** [comment]
Both of those fields don't save with version 7.2.1 either...
