### ISSUE TITLE
Unable to save old announcements

### ISSUE THREAD

**Issue by krlaframboise** [DNNCommunity/DNN.Announcements#30]
## Describe the bug
Unable to save announcements created in version 4.0.3

## Software Versions
- DNN: 09.02.02
- Module: 07.02.01

## To Reproduce
1. Open an announcement created with version 4.0.3 and click Update

## Error log
Error: is currently unavailable. DotNetNuke.Services.Exceptions.ModuleLoadException: The INSERT statement conflicted with the FOREIGN KEY constraint "FK_ContentItems_MetaData_ContentItems". The conflict occurred in database "TEST_DNN", table "dbo.ContentItems", column 'ContentItemID'. The statement has been terminated. ---> System.Data.SqlClient.SqlException: The INSERT statement conflicted with the FOREIGN KEY constraint "FK_ContentItems_MetaData_ContentItems". The conflict occurred in database "TEST_DNN", table "dbo.ContentItems", column 'ContentItemID'. The statement has been terminated. at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose) at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady) at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted) at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest) at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry) at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry) at System.Data.SqlClient.SqlCommand.ExecuteNonQuery() at PetaPoco.Database.Execute(String sql, Object[] args) at DotNetNuke.Data.PetaPoco.PetaPocoHelper.ExecuteNonQuery(String connectionString, CommandType type, Int32 timeoutSec, String sql, Object[] args) at DotNetNuke.Data.SqlDataProvider.ExecuteNonQuery(String procedureName, Object[] commandParameters) at DotNetNuke.Entities.Content.Data.DataService.AddMetaData(ContentItem contentItem, String name, String value) at DotNetNuke.Entities.Content.Data.DataService.SynchronizeMetaData(ContentItem contentItem, IEnumerable`1 added, IEnumerable`1 deleted) at DotNetNuke.Entities.Content.ContentController.SaveMetadataDelta(ContentItem contentItem) at DotNetNuke.Entities.Content.ContentController.UpdateContentItem(ContentItem contentItem) at DotNetNuke.Modules.Announcements.Components.Business.AnnouncementsController.UpdateAnnouncement(AnnouncementInfo announcement) at DotNetNuke.Modules.Announcements.MVP.Presenters.AnnouncementsEditPresenter.UpdateAnnouncement(Object sender, EditItemEventArgs e) at DotNetNuke.Modules.Announcements.AnnouncementsEdit.CmdUpdateClick(Object sender, EventArgs e) --- End of inner exception stack trace ---

**Comment by thogan44** [comment]
`        public void UpdateAnnouncement(AnnouncementInfo announcement)
        {

            using (IDataContext context = DataContext.Instance())
            {
                var repository = context.GetRepository<AnnouncementInfo>();

                var objContentItem = new ContentItem
                {
                    ContentItemId = announcement.ContentItemID,
                    Content = announcement.Description,
                    ContentTitle = announcement.Title,
                    Indexed = false,
                    ModuleID = announcement.ModuleID,
                    TabID = Null.NullInteger,
                    ContentKey = null,
                    ContentTypeId = 4
                };

                if (objContentItem.ContentItemId == 0)
                {
                    announcement.ContentItemID = new ContentController().AddContentItem(objContentItem);
                }
                else
                {
                    new ContentController().UpdateContentItem(objContentItem);
                }

                repository.Update(announcement);

            }

        }`
See the statement if (objContentItem.ContentItemId == 0) it was if (objContentItem.ContentItemId == Null.NullInteger) 

I changed it to 0 because if objContentItem.ContentItemId from the database was null it would return 0. and besides how often will the ContentItemId be 0 anyway even on a fresh DNN install.
