### ISSUE TITLE
Error in Add/Edit Announcement screen

### ISSUE THREAD

**Issue by jdaniels517** [DNNCommunity/DNN.Announcements#32]
I just upgraded to the latest version of DNN from version 7.??.  The ole Announcements module wasn't working so I downloaded the latest from here.  Install worked great but have an exception on the Add/Edit Announcement screen (see below).  I can successfully add/edit an announcement but the error won't go away.  Any help is appreciated.

An error has occurred. DotNetNuke.Services.Exceptions.ModuleLoadException: Height must be non negative. Parameter name: value ---> System.ArgumentOutOfRangeException: Height must be non negative. Parameter name: value at System.Web.UI.WebControls.Style.set_Height(Unit value) at Telerik.Web.UI.RadEditor.set_Height(Unit value) at DotNetNuke.Providers.RadEditorProvider.EditorProvider.set_Height(Unit value) at DotNetNuke.UI.UserControls.TextEditor.OnLoad(EventArgs e) --- End of inner exception stack trace ---

**Comment by krlaframboise** [comment]
Go into the settings and fill in the "Editor Height" field.  I believe 300 used to be the default value.

Can you do me a favor and change the template of one module and see if it changes the template of all the Announcements modules on that portal?  Before I create a new issue for it I want to rule out something specific to my install...

**Comment by jdaniels517** [comment]
Thanks adjusting that setting fixed the issue I reported.

I did change the template and it changed it for all other instances of the
module.


Jamie Daniels
President
Anchor Data Systems
(217) 891-5719

**Comment by hansonrf** [comment]
Same issue.  Fix worked.  Kudos

**Comment by valadas** [comment]
Fixed in #46 will get out with 7.2.2
