### ISSUE TITLE
Module Specific Templates Are No Longer Supported

### ISSUE THREAD

**Issue by krlaframboise** [DNNCommunity/DNN.Announcements#33]
## Describe the bug
The template fields used to be stored in the module settings table which allowed each module to have a unique template, but the latest version stores each template field as an html file on the web server.  

Changing the template from any module changes the template for every module across all portals so you can't have more than one template.

Another problem is that the Template Configuration screen shows fields for Separator Template and Alternate Item Template, but it doesn't save changes made to those fields and manually changing those template files on the server has no effect on the output of the Announcements.

## Software Versions
- DNN: 09.02.02
- Module: 07.02.01

## Expected behavior
 - All the fields shown in the Template Configuration should be used when rendering the Announcements.  Either fix that problem or remove those fields.
 - The Template fields should be stored in the database so that each module can use a different template like you used to be able to do.  If that's not an option then there needs to be a way to point each module at a specific folder containing the template field files so that users can create multiple template folders and select which one to use for each module.

**Comment by valadas** [comment]
For the not saving issue, it was fixed in #49 and will be released in 7.2.2 soon.

For the feature to have module specific templates, this was not present on v4 taken from codeplex, what version do you have that has this feature and where was it taken from?

**Comment by mattmol** [comment]
Were templates removed officially from this release?
My templated announcements have become completely useless without the templates upon upgrade.
And I need to finally bite the bullet and upgrade due to Telerik removal
