### ISSUE TITLE
Announcements import/export

### ISSUE THREAD

**Issue by hansonrf** [DNNCommunity/DNN.Announcements#34]
I can export but import seems to fail (no observable data)

Export from DNN 7.3.4/Announcements 4.0.3 gets an XML file content.DNNAnnouncements.Announcements.xml

Copy it to DNN 9.3.2.24/7.2.1 and refresh everything.

On import, the module is there but after thinking a few seconds the page returns but no data is there.

**Comment by valadas** [comment]
Import/Export in Dnn is not made to be used across different versions. It is maybe not impossible, but not something easy to implement. I am closing this issue for now but if anyone has intentions to add that, please do comment or reopen
