### ISSUE TITLE
Expired filter ignored when logged out.

### ISSUE THREAD

**Issue by bitzblitz** [DNNCommunity/DNN.Announcements#4]
I wish to have two views of announcements on my site. I have one page that shows current announcements and a second page that shows archived (past) announcements. So on one page I have the module set to show _Current_ view and on the archive page I have it set to show _Expired_ announcements. While I'm logged in **Edit** Mode the content looks fine, but when I log out, the Archived announcements shows Current announcements instead of the expected Expired announcements.

**Comment by bitzblitz** [comment]
Although I was able to reproduce the issue several times before posting, I tried a simplified steps to reproduce and now the settings seem to stick. Perhaps the order of operations I did before caused a problem.

So it seems to work as expected with my current scenario.

**Comment by bitzblitz** [comment]
I discovered the actual problem: The filter is ignored once you leave **Edit** mode. So it is not possible to have one module showing "Current" announcements and another showing "Expired" announcements.

I think this is a bug.

**Comment by trouble2** [comment]
Looks more like an issue with the way it saves the settings. 
When I look at the tabmodulesettings and modulesettings table, they both seem to have entries for the module settings for the announcements module, so I can see things like 'defaultviewtype' set to expired, or current in both tables....

**Comment by valadas** [comment]
Closing this issue as I could not reproduce and did not get a reply since Aug 2018. Feel free to comment if there is any news.
