### ISSUE TITLE
Updating Announcement - Release 7.0.2 Foreign Key Insert Error

### ISSUE THREAD

**Issue by HZass** [DNNCommunity/DNN.Announcements#43]
## Describe the bug
Update an existing announcement result in the critical error.

## Software Versions
- DNN: 08.04.03
             09.02.02
- Module: 07.02.01

## Screenshots
Following is the Error Report:
👍 Error: is currently unavailable. DotNetNuke.Services.Exceptions.ModuleLoadException: The INSERT statement conflicted with the FOREIGN KEY constraint "FK_ContentItems_MetaData_ContentItems". The conflict occurred in database "vwcorgASL2UCviemA_804T", table "dbo.ContentItems", column 'ContentItemID'. The statement has been terminated. ---> System.Data.SqlClient.SqlException: The INSERT statement conflicted with the FOREIGN KEY constraint "FK_ContentItems_MetaData_ContentItems". The conflict occurred in database "vwcorgASL2UCviemA_804T", table "dbo.ContentItems", column 'ContentItemID'. The statement has been terminated. at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose) at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady) at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted) at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest) at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry) at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry) at System.Data.SqlClient.SqlCommand.ExecuteNonQuery() at PetaPoco.Database.Execute(String sql, Object[] args) at DotNetNuke.Data.SqlDataProvider.ExecuteNonQuery(String procedureName, Object[] commandParameters) at DotNetNuke.Entities.Content.Data.DataService.SynchronizeMetaData(ContentItem contentItem, IEnumerable`1 added, IEnumerable`1 deleted) at DotNetNuke.Entities.Content.ContentController.UpdateContentItem(ContentItem contentItem) at DotNetNuke.Modules.Announcements.Components.Business.AnnouncementsController.UpdateAnnouncement(AnnouncementInfo announcement) at DotNetNuke.Modules.Announcements.MVP.Presenters.AnnouncementsEditPresenter.UpdateAnnouncement(Object sender, EditItemEventArgs e) at DotNetNuke.Modules.Announcements.AnnouncementsEdit.CmdUpdateClick(Object sender, EventArgs e) --- End of inner exception stack trace ---

## Error log
**Note: Debug DLL's**
Please replace the current extension DLL's with the debug DLL's (if these are available with the release) and reproduce the error with the debug DLL's before pasting the error log.

Paste the error log that is related to this issue.

**Comment by valadas** [comment]
Can you give some exact steps to reproduce, was this a clean 9.2.2 Dnn and 7.2.1 module or an upgrade from which version, etc.

**Comment by HZass** [comment]
In the case of Announcements running on 8.0.4, this was not an upgrade in DNN; but just an update in the Announcement Module.  
In the case of Announcements running on DNN 9.2.2, this was an upgrade from DNN 8.0.,4.

The steps to create the issue:
Select an existing Announcement on a page in the Edit Mode.
Make a minor change in the test
Initiate the Update control
Immediately received the above Event Log message

I did notice that a new column for Announcement in 7.0.x for the ContentItem ID was added.  The database filled this column with NULL values in all cases.  This could cause the issue of a foreign key error.

**Comment by HZass** [comment]
I had updated the DNN Announcement Module to the latest version from Release 4.0.3

**Comment by valadas** [comment]
Thank you, this is very good info

**Comment by valadas** [comment]
Fixed in #48 and will be available shortly in release 7.2.2
