### ISSUE TITLE
Muliple errors with depricated api's in DNN 9.2

### ISSUE THREAD

**Issue by muddeatr** [DNNCommunity/DNN.Announcements#5]
There are multiple errors with the Announcement module using deprecated API's in DNN 9.2
Below is one example. 

Error: Announcements is currently unavailable. DotNetNuke.Services.Exceptions.ModuleLoadException: Method not found: 'System.String DotNetNuke.Entities.Modules.ModuleController.CacheKey(Int32)'. ---> System.MissingMethodException: Method not found: 'System.String DotNetNuke.Entities.Modules.ModuleController.CacheKey(Int32)'. at DotNetNuke.Modules.Announcements.Announcements..ctor() at ASP.desktopmodules_announcements_announcements_ascx..ctor() at __ASP.FastObjectFactory_app_web_bnqtvai1.Create_ASP_desktopmodules_announcements_announcements_ascx() at System.Web.Compilation.BuildResultCompiledType.CreateInstance() at System.Web.UI.TemplateControl.LoadControl(IWebObjectFactory objectFactory, VirtualPath virtualPath, Type t, Object[] parameters) at System.Web.UI.TemplateControl.LoadControl(VirtualPath virtualPath) at DotNetNuke.UI.ControlUtilities.LoadControl[T](TemplateControl containerControl, String ControlSrc) at DotNetNuke.UI.Modules.WebFormsModuleControlFactory.CreateModuleControl(TemplateControl containerControl, ModuleInfo moduleConfiguration) at DotNetNuke.UI.Modules.ModuleControlFactory.LoadModuleControl(TemplateControl containerControl, ModuleInfo moduleConfiguration) at DotNetNuke.UI.Modules.ModuleHost.LoadModuleControl() --- End of inner exception stack trace ---

**Comment by TopCat6** [comment]
Concur... same experience.
