### ISSUE TITLE
Wrong TabModuleSettings may be used in shared module

### ISSUE THREAD

**Issue by GTSageDev** [DNNCommunity/DNN.Announcements#51]
When an Announcements module is shared on more than 1 tab, and a different viewtype is used in each tab, the actual viewtype used is unpredictable.
I think this is caused in the constructor for Settings
var moduleInfo = new ModuleController().GetModule(_moduleId);
The sp GetModule(_moduleID,null) returns multiple rows (1 per tab) and the first one is used, which may relate to the wrong tab, so TabModuleSettings may be wrong.
GetModule(_moduleId) needs to be called with the tabID parameter

## Software Versions
- DNN: 9.4
- Module: 7.2.2.

## To Reproduce

1. Add an announcements module with a few expired/current/future announcements and viewtype all
2. Share the module to another tab with a different view type
4. Both tabs will use the same view - probably from the first tab

## Expected behaviour

Each instance of the shared module should be able to have a different view

**Comment by GTSageDev** [comment]
Suggested updated code in Components\Settings\Settings.cs
```
    //var moduleInfo = new ModuleController().GetModule(_moduleId);
    //ModuleSettings = moduleInfo.ModuleSettings;
    //TabModuleSettings = moduleInfo.TabModuleSettings;
    foreach (ModuleInfo modInfo in (new ModuleController()).GetTabModulesByModule(_moduleId))
    {
	if (modInfo.TabModuleID == _tabModuleId)
	{
	    ModuleSettings = modInfo.ModuleSettings;
	    TabModuleSettings = modInfo.TabModuleSettings;
	    break;
	}
    }
```
Hope this helps

**Comment by EPTamminga** [comment]
Are you able to submit a Pull Request?

**Comment by GTSageDev** [comment]
Will give it a go – there’s a first time for everything!

Geoff

**Comment by EPTamminga** [comment]
First time is challeging, but you will get the hang of it. PR'S for modules are easier to start with than the full DNN platform repo PR's. Succes!
