### ISSUE TITLE
Invalid Columns while upgrading the module

### ISSUE THREAD

**Issue by ElBafo** [DNNCommunity/DNN.Announcements#65]
We are trying to upgrade the module in a client's installation and we get this error:

Install Package::dnn_Announcements6

Info::Starting Installation

Info::Starting Installation - DNN_Announcements

Info::Starting Installation - Script

Info::Begin Sql execution

Info::Creating backup of previous version - 03.03.05.SqlDataProvider

Info::Created - 03.03.05.SqlDataProvider

Info::Executing 03.03.05.SqlDataProvider

Info::Start Sql execution: 03.03.05.SqlDataProvider file

Info::SQL Execution resulted in following Exceptions: System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'CreatedByUser'. Invalid column name 'CreatedDate'. at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose) at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady) at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite) at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry) at System.Data.SqlClient.SqlCommand.ExecuteNonQuery() at DotNetNuke.Data.SqlDatabaseConnectionProvider.ExecuteNonQuery(String connectionString, CommandType commandType, Int32 commandTimeout, String query) at DotNetNuke.Data.SqlDataProvider.ExecuteScriptInternal(String connectionString, String script, Int32 timeoutSec) ClientConnectionId:c8bcbd99-f01f-46c7-adb1-f2cc4adfe3fe Error Number:207,State:1,Class:16 /** Create Stored Procedures **/ CREATE procedure dbo.GetAnnouncements @ModuleId int, @StartDate datetime, @EndDate datetime as select Announcements.ItemId, Announcements.ModuleId, Announcements.CreatedByUser, Announcements.CreatedDate, Announcements.Title, Announcements.URL, Announcements.Description, Announcements.ViewOrder, Announcements.PublishDate, UrlTracking.TrackClicks, UrlTracking.NewWindow from Announcements left outer join UrlTracking on Announcements.URL = UrlTracking.Url and UrlTracking.ModuleId = @ModuleID where Announcements.ModuleId = @ModuleId and (Announcements.ExpireDate > GetDate() or Announcements.ExpireDate is null) and ( ((Announcements.PublishDate >= @StartDate) or @StartDate is null) and ((Announcements.PublishDate <= @EndDate) or @EndDate is null) ) order by Announcements.ViewOrder asc, Announcements.PublishDate desc

Info::End Sql execution: 03.03.05.SqlDataProvider file

Info::Finished Sql execution

Info::Installation Failed - Script

Info::Installation Failed - DNN_Announcements

Info::Deleted temporary install folder

Info::Installation Failed

Any help appreciated

**Comment by valadas** [comment]
Hi @ElBafo , From which version was the upgrade from and do you know if the instance uses a custom database owner ?

**Comment by valadas** [comment]
Closing this issue due to lack of response

**Comment by ElBafo** [comment]
@valadas , I must have missed the email notification of your reply. Thank you for closing this issue and please accept my sincere apology.

We didn't came across this issue again.
