### ISSUE TITLE
'Delete unauthorized Uses' option is not present in DNN version 9.11 & 9.13

### ISSUE THREAD

**Issue by DeepashriDatar** [DNNCommunity/DNN.Announcements#74]
It is easy to delete all the unauthorized users in one go.
Deleting each user one by one is time consuming. 

It was present in version 7.04

**Comment by Timo-Breumelhof** [comment]
I think you should have logged this @ https://github.com/dnnsoftware/Dnn.Platform/issues ?

**Comment by valadas** [comment]
Yes, this is not about this specific module. There are however a couple of modules that a specialized at better user management. You can google "Dnn User Management" and you should find some, I remember also seeing some posts about this in the community forums here https://dnncommunity.org/forums
