### ISSUE TITLE
DNN 9.2 Support is not working properly

### ISSUE THREAD

**Issue by AlexanderAllmendinger** [DNNCommunity/DNN.Announcements#8]
Hello,
I was just updating our DNN Portal to the new released 9.2 and noticed the Announcements Module stopped working. Thanks to the description on this GitHub Project I was able to get the latest source code and build it. I was also able to install the new module version but unfortunately it didn't work for me. I'm always receiving the following Exception:

> UserAgent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/17.17134
> ExceptionHash:aNkuhHvYN2hV/1TE6d6Ev9whq3Q=
> Message:Object reference not set to an instance of an object.
> StackTrace:
> 
> 
> InnerMessage:Object reference not set to an instance of an object.
> InnerStackTrace:
> at DotNetNuke.Modules.Announcements.Components.Business.AnnouncementInfo.GetProperty(String strPropertyName, String strFormat, CultureInfo formatProvider, UserInfo AccessingUser, Scope AccessLevel, Boolean& PropertyNotFound) at DotNetNuke.Services.Tokens.BaseCustomTokenReplace.replacedTokenValue(String objectName, String propertyName, String format) at DotNetNuke.Services.Tokens.BaseTokenReplace.ReplaceTokens(String sourceText) at DotNetNuke.Modules.Announcements.Components.Template.SimpleTemplate.RenderTemplate(IEnumerable`1 announcements, Boolean editEnabled) at DotNetNuke.Modules.Announcements.MVP.Presenters.AnnouncementsViewPresenter.GetRenderedTemplate(Object sender, EventArgs e) at DotNetNuke.Modules.Announcements.AnnouncementsView.OnLoad(EventArgs e) at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

Any chance that one of you is creating a new release package which I can use for installation? Just in case something didn't work correctly with the build?

Thanks

**Comment by mattmol** [comment]
Is there any way to make a new RELEASE with the update for 9.2?
I don't have visual studio to compile this...

**Comment by valadas** [comment]
@mattmol You can get the release zip files in the end of the comments on this pull request: https://github.com/DNNCommunity/DNN.Announcements/pull/6

@EPTamminga should also publish that release shortly ( I do not have write access ).

Also, if you see everything works fine in Dnn 9.2, please close this issue and if you run into any problems, please create an issue and I will correct promptly.

**Comment by EPTamminga** [comment]
Release DNN.Announcements 07.02.00 posted, this version is DNN 9.2.0 compliant.
